name: Deploy docker image
on:
  push:
    branches:
      - 'main'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      # Build JAR:
      - uses: actions/checkout@v2

      # Set global environment variables:
      - name: set global env
        id: global_env
        run: |
          IMAGE_NAME_LOWERCASE=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=IMAGE_NAME::${IMAGE_NAME_LOWERCASE}"
          DOCKERHUB_IMAGE_NAME_LOWERCASE="docker.pkg.github.com/${IMAGE_NAME_LOWERCASE}/${IMAGE_NAME_LOWERCASE#*/}"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::${DOCKERHUB_IMAGE_NAME_LOWERCASE}"


      # Build Docker image:
      - name: Build and tag image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      # Publish image to github package repository:
      - name: Publish image
        run: docker push "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}"
